<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'TANQR') }}</title>

    @livewireStyles


    <!-- Scripts -->
    @vite(['resources/css/app.css', 'resources/js/app.js'])

    <link rel="stylesheet" href="{{ asset('css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/flowbite.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/index.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/output.css') }}">
    <link href="{{ asset('css/css2.css') }}" rel="stylesheet">

    <style>
        .main-color {
            color: #FBD400;
        }

        .main-color-hover:hover {
            color: white; /* Change this to the desired hover color for the main color */
        }

        .secondary-color {
            color: red;
        }

        .secondary-color-hover:hover {
            color: white; /* Change this to the desired hover color for the secondary color */
        }
        .main-color-bg {
            background-color: #FBD400;
        }
        .main-color-bg-hover:hover {
            background-color: #FBD400; /* Change this to the desired hover color for the main color */
            color: white;
        }
        .icon-hover:hover {
            color: #FBD400; /* Change this to the desired hover color for the main color */
        }


        .box-button {
            color: #FBD400;
        }

        .box-button:hover {
            background-color: #FBD400;
            color: white;
        }

        .box-button:hover .icon-svg {
            stroke: white !important;;
        }

        .icon-svg {
            fill: #FBD400;
        }

    </style>



    <style>

        @import url(//fonts.googleapis.com/css?family=Lato:300:400);

        /*.bodyGradient {*/
        /*    position:relative;*/
        /*    text-align:center;*/
        /*    background: linear-gradient(to bottom left, #2D3A89 0%, rgba(84, 58, 183, 1) 50%, rgba(0, 172, 193, 1) 100%);*/
        /*    color:white;*/
        /*}*/

        .waves {
            position:relative;
            width: 100%;
            height:15vh;
            margin-bottom:-7px; /*Fix for safari gap*/
            min-height:100px;
            max-height:150px;
        }





        /* Animation */

        .parallax > use {
            animation: move-forever 25s cubic-bezier(.55,.5,.45,.5)     infinite;
        }
        .parallax > use:nth-child(1) {
            animation-delay: -2s;
            animation-duration: 7s;
        }
        .parallax > use:nth-child(2) {
            animation-delay: -3s;
            animation-duration: 10s;
        }
        .parallax > use:nth-child(3) {
            animation-delay: -4s;
            animation-duration: 13s;
        }
        .parallax > use:nth-child(4) {
            animation-delay: -5s;
            animation-duration: 20s;
        }
        @keyframes move-forever {
            0% {
                transform: translate3d(-90px,0,0);
            }
            100% {
                transform: translate3d(85px,0,0);
            }
        }
        /*Shrinking for mobile*/
        @media (max-width: 768px) {
            .waves {
                height:40px;
                min-height:40px;
            }
            .content {
                height:30vh;
            }
            h1 {
                font-size:24px;
            }
        }

        .text-color-primary{
            text-decoration-color:#FBD400 ;
        }

    </style>



    <style>
        /* ----------------------------------------------
        * Generated by Animista
        * w: http://animista.net, t: @cssanimista
        * ---------------------------------------------- */

        .slide-in-bottom{-webkit-animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) both;animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) both}
        .slide-in-bottom-h1{-webkit-animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) .5s both;animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) .5s both}
        .slide-in-bottom-subtitle{-webkit-animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) .75s both;animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) .75s both}
        .fade-in{-webkit-animation:fade-in 1.2s cubic-bezier(.39,.575,.565,1.000) 1s both;animation:fade-in 1.2s cubic-bezier(.39,.575,.565,1.000) 1s both}
        .bounce-top-icons{-webkit-animation:bounce-top .9s 1s both;animation:bounce-top .9s 1s both}

        @-webkit-keyframes slide-in-bottom{0%{-webkit-transform:translateY(1000px);transform:translateY(1000px);opacity:0}100%{-webkit-transform:translateY(0);transform:translateY(0);opacity:1}}@keyframes slide-in-bottom{0%{-webkit-transform:translateY(1000px);transform:translateY(1000px);opacity:0}100%{-webkit-transform:translateY(0);transform:translateY(0);opacity:1}}
        @-webkit-keyframes bounce-top{0%{-webkit-transform:translateY(-45px);transform:translateY(-45px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in;opacity:1}24%{opacity:1}40%{-webkit-transform:translateY(-24px);transform:translateY(-24px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}65%{-webkit-transform:translateY(-12px);transform:translateY(-12px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}82%{-webkit-transform:translateY(-6px);transform:translateY(-6px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}93%{-webkit-transform:translateY(-4px);transform:translateY(-4px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}25%,55%,75%,87%{-webkit-transform:translateY(0);transform:translateY(0);-webkit-animation-timing-function:ease-out;animation-timing-function:ease-out}100%{-webkit-transform:translateY(0);transform:translateY(0);-webkit-animation-timing-function:ease-out;animation-timing-function:ease-out;opacity:1}}@keyframes bounce-top{0%{-webkit-transform:translateY(-45px);transform:translateY(-45px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in;opacity:1}24%{opacity:1}40%{-webkit-transform:translateY(-24px);transform:translateY(-24px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}65%{-webkit-transform:translateY(-12px);transform:translateY(-12px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}82%{-webkit-transform:translateY(-6px);transform:translateY(-6px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}93%{-webkit-transform:translateY(-4px);transform:translateY(-4px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}25%,55%,75%,87%{-webkit-transform:translateY(0);transform:translateY(0);-webkit-animation-timing-function:ease-out;animation-timing-function:ease-out}100%{-webkit-transform:translateY(0);transform:translateY(0);-webkit-animation-timing-function:ease-out;animation-timing-function:ease-out;opacity:1}}
        @-webkit-keyframes fade-in{0%{opacity:0}100%{opacity:1}}@keyframes fade-in{0%{opacity:0}100%{opacity:1}}

        .custom-red-bg {
            background-color: #AF0A35;
        }

        .custom-red-text {
            color: #AF0A35;
        }
        .bg-custom {
            /*background-image: url('http://96.46.181.165/projects/School/public/images/bg.svg');*/
            background-size: cover;
            background-position: right;
        }
        footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            background-color: #AF0A35; /* Optional background color */
            color: white; /* Optional text color */
            padding: 10px; /* Optional padding */
            text-align: center; /* Optional text alignment */
        }
    </style>


</head>
<body class="leading-normal tracking-normal text-gray-900 bg-custom" style="font-family: 'Roboto', sans-serif">

<main class="">


    <div class="relative flex justify-top ">

        <!-- Content -->
        <div class="w-full md:w-1/2 ">

            <div class="flex flex-col after:flex-1 justify-end">

                <!-- Header -->
                <div class="flex-1 justify-start items-start flex mt-0">
                    <div class="flex items-start justify-between h-25 px-4 sm:px-6 lg:px-8">
                        <!-- Logo -->
                        <a class="block mt-2 flex items-center" href="{{ route('login') }}">
                            <img class="mt-1" src="{{ asset('/images/finca.png') }}"
                                 height="200" width="200" alt="Authentication decoration" />
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </div>







    <div class="pb-14 bg-right bg-cover" >


        <!--Main-->
        <div class="container pt-14 md:pt-28 px-6 mx-auto mt-8">

            <div class=" flex justify-between w-full">
                <!--Left Col-->
                <div class="overflow-y-hidden w-full">


                    <h1 class="text-4xl font-bold leading-tight slide-in-bottom-h1 text-gray-800">Welcome to the <br> Merchant Management<br> System...</h1>
                    <p class="leading-normal text-base text-2xl mb-8  slide-in-bottom-subtitle text-gray-500">
                        Empowering your financial institution <br> with seamless management and operational efficiency!
                    </p>



                </div>


                <!--Right Col-->
                <div class="w-full xl:w-3/5 py-6 overflow-y-hidden">
                    <div id="xx" class="max-w-sm px-4 py-8 bg-gray-100 self-center rounded-xl shadow-md shadow-gray-200 " style="margin: 0 auto; width: 400px">

                        {{ $slot }}
                    </div>


                </div>


            </div>


            <!--Footer-->
            <div class="w-full pt-4 pb-6 text-sm md:text-left fade-in mt-2">

                <p class="custom-red-text font-bold pb-8 lg:pb-6 md:text-left fade-in">Powered by:</p>
                <div class="flex w-full md:justify-start pb-24 lg:pb-0 fade-in">

                    <ul class="max-w-md space-y-1 text-gray-500 list-inside dark:text-gray-400">
{{--                        <li class="flex items-center">--}}
{{--                            <svg class="w-3.5 h-3.5 mr-2 custom-red-text dark:text-green-400 flex-shrink-0 bounce-top-icons" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">--}}
{{--                                <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z"/>--}}
{{--                            </svg>--}}
{{--                            National Bank of Commerce (NBC) Limited Tanzania.--}}
{{--                        </li>--}}
                        <li class="flex items-center">
                            <svg class="w-3.5 h-3.5 mr-2 custom-red-text dark:text-green-400 flex-shrink-0 bounce-top-icons" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z"/>
                            </svg>
                            Moira Limited
                        </li>
                        <li class="flex items-center">
                            <svg class="w-3.5 h-3.5 mr-2 custom-red-text dark:text-gray-400 flex-shrink-0 bounce-top-icons" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z"/>
                            </svg>
                            Tan QR

                        </li>
                    </ul>
                </div>
                <a class="text-gray-500 no-underline hover:no-underline" href="#">&copy; Moira 2023</a>
            </div>

        </div>


    </div>




    <div class="flex justify-center items-center rounded-lg" >

        <div class="fixed left-0 right-0 bottom-0">
            <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 28" preserveAspectRatio="none" shape-rendering="auto">
                <defs>
                    <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
                </defs>
                <g class="parallax">
                    <use xlink:href="#gentle-wave" x="48" y="3" fill="#AF0A35" />
                    <use xlink:href="#gentle-wave" x="48" y="5" fill="#FFFFFF" >  </use>
                    <use xlink:href="#gentle-wave" x="48" y="7" fill="#003E7E" />
                    <use xlink:href="#gentle-wave" x="48" y="9" fill="#003E7E" />
                </g>
            </svg>
        </div>
    </div>
</main>
@livewireScripts

<script src="{{ asset('js/cdn.min.js') }}" defer></script>
<script src="{{ asset('js/flowbite.js') }}" defer></script>
<script src="{{ asset('js/index.min.js') }}" defer></script>
<script src="{{ asset('js/jquery.js') }}" defer></script>
</body>
</html>

